import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css';
import NavigationMenu from "@/components/NavigationMenu";
import { Geist, Geist_Mono } from "next/font/google";
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import "./globals.sass";
import Header from "@/components/Header";
import { ApolloWrapper } from "@/lib/apollo-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ApolloWrapper>

          <Header />
          <Container fluid>
            <Row className="flex-nowrap">
                <NavigationMenu />
              <Col>
                {children}
              </Col>
            </Row>
          </Container>
        </ApolloWrapper>
      </body>
    </html>
  );
}
