import type { Metadata } from "next";
import NavigationMenu from "@/components/NavigationMenu"; 
import { Geist, Geist_Mono } from "next/font/google";
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import "./globals.sass";
import Link from "next/link";
import Image from "next/image";
import Ava from '@/assets/images/ava.png'
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <Container fluid>
          <Row>
            <Col  className="p-[0] bg-white max-w-[250px]">
            <NavigationMenu /> 
            </Col>
            <Col>
              {children}
            </Col>
          </Row>
        </Container>
      </body>
    </html>
  );
}
